"Correction maj-pacman. Scripts en cours"

diff --git a/iso2usb b/iso2usb
--- a/iso2usb
+++ b/iso2usb
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 #
 #
-# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2013-2015
+# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2013-2016
 #
-# VERSION 5
+# VERSION 6
 #
 # AVEC 1 paramètre : /path/to/archlinux.iso
 # Example : $ iso2usb ~/99-Isos/archlinux-2012.12.01-dual.iso
@@ -13,47 +13,66 @@
 #
 
 # COULEURS
-ALL_OFF="\e[1;0m"
-BOLD="\e[1;1m"
-BLUE="${BOLD}\e[1;34m"
-GREEN="${BOLD}\e[1;32m"
-RED="${BOLD}\e[1;31m"
-YELLOW="${BOLD}\e[1;33m"
+Bold=$(tput bold)
+Underline=$(tput sgr 0 1)
+Reset=$(tput sgr0)
+# Regular Colors
+Red=$(tput setaf 1)
+Green=$(tput setaf 2)
+Yellow=$(tput setaf 3)
+Blue=$(tput setaf 4)
+Purple=$(tput setaf 5)
+Cyan=$(tput setaf 6)
+White=$(tput setaf 7)
+# Bold
+BRed=${Bold}$(tput setaf 1)
+BGreen=${Bold}$(tput setaf 2)
+BYellow=${Bold}$(tput setaf 3)
+BBlue=${Bold}$(tput setaf 4)
+BPurple=${Bold}$(tput setaf 5)
+BCyan=${Bold}$(tput setaf 6)
+BWhite=${Bold}$(tput setaf 7)
+
 
 # FONCTIONS
 msg_titre() {
-        local mesg=$1; shift
-        printf "${BOLD}${mesg}${ALL_OFF}\n" "$@" >&2
+    local mesg=$1; shift
+    printf "${BWhite}${mesg}${Reset}\n" "$@" >&2
 }
 
 msg() {
-        local mesg=$1; shift
-        printf "${BOLD}:: ${mesg}${ALL_OFF}\n" "$@" >&2
+    local mesg=$1; shift
+    printf "${BWhite}:: ${mesg}${Reset}\n" "$@" >&2
 }
 
-msg_grenn() {
-        local mesg=$1; shift
-        printf "${GREEN}:: ${mesg}${ALL_OFF}\n" "$@" >&2
+msg_green() {
+    local mesg=$1; shift
+    printf "${BGreen}:: ${mesg}${Reset}\n" "$@" >&2
+}
+
+msg_newline() {
+    local mesg=$1; shift
+    printf "\n" "$@" >&2
 }
 
 error() {
-        local mesg=$1; shift
-        printf "${RED}==> ERREUR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+    local mesg=$1; shift
+    printf "${BRed}==> ERREUR:${Reset}${BWhite} ${mesg}${Reset}\n" "$@" >&2
 }
 
 cleanup() {
-        [[ $1 ]] && exit $1
+    [[ $1 ]] && exit $1
 }
 
 die() {
-        error "$*"
-        cleanup 1
+    error "$*"
+    cleanup 1
 }
 
 read_key() {
-    echo -e "${YELLOW}"
+    printf '%s' "${BYellow}"
     read -p "$1 et appuyer sur une touche" OPTION
-    echo -e "${ALL_OFF}"
+    printf '%s' "${Reset}"
 }
 
 contains_element() {
@@ -62,7 +81,7 @@ contains_element() {
 }
 
 invalid_option() {
-    echo -e "${RED}Option invalide. Essayez une autre option.${ALL_OFF}"
+    printf '%s\n' "${BRed}Option invalide. Essayez une autre option.${Reset}"
 }
 
 # Variables globales
@@ -77,9 +96,9 @@ nombre_d_argument="$#"
 path_to_iso="$1"
 
 # => Passe en root
-if [ ! $( id -u ) -eq 0 ]; then
-    echo -e "\n${YELLOW}Le script "$0" doit être exécuté en << root >>."
-    echo -e "Entrer le mot de passe de << root >>${ALL_OFF}"
+if (( EUID != 0 )); then
+    printf '\n%s\n' "${BYellow}Le script $0 doit être exécuté en «root»."
+    printf '%s\n' "Entrer le mot de passe de «root»${Reset}"
     exec su -c "${0} ${1}"
     exit ${?}
 fi
@@ -103,7 +122,7 @@ else
     # Pas d'argument. Fabrique une liste des isos
     liste_isos=($(LC_ALL=C ls "${DIR_ISOS}" | grep -E ".iso$"))
     PS3="Entrer le n° de l'option choisie: "
-    echo -e "\n${BOLD}Sélectionner le fichier iso à graver sur USB :${ALL_OFF}"
+    printf '\n%s\n' "${BWhite}Sélectionner le fichier iso à graver sur USB :${Reset}"
     select CHOIX_ISO in "${liste_isos[@]}"; do
         if contains_element "$CHOIX_ISO" "${liste_isos[@]}"; then
             break
@@ -114,7 +133,7 @@ else
     PATH_TO_ISO="${DIR_ISOS}/${CHOIX_ISO}"
 fi
 
-echo ""
+msg_newline
 msg "L'ISO suivante sera écrite sur la clé USB : ${PATH_TO_ISO}"
 
 # date +%Y-%m-%d" "%H:%M:%S => 2012-12-13 19:46:11
